export const PLACES = [
  {
    id: 1,
    name: 'The Body Shop',
    address: 'Boulebar Nørregade 25',
    lat: 55.6812,
    lng: 12.571,
    description: 'Refill af udvalgte kropsplejeprodukter. Medbring tom flaske.',
    categories: ['Shampoo', 'Balsam', 'Sæbe'],
    productSummary: 'Shampoo, Balsam, Sæbe',
    products: [
      { name: 'Shea Shampoo', price: 'fra 45 kr / 100 ml', category: 'Shampoo', inStock: true },
      { name: 'Ginger Balsam', price: 'fra 45 kr / 100 ml', category: 'Balsam', inStock: true },
      { name: 'Håndsæbe', price: 'fra 35 kr / 100 ml', category: 'Sæbe', inStock: true },
    ],
    rating: 4.6,
  },
  {
    id: 2,
    name: 'Løs Market',
    address: 'Vesterbrogade 120, København',
    lat: 55.6704,
    lng: 12.5447,
    description: 'Københavns første emballagefri supermarked. Medbring dine egne beholdere.',
    categories: ['Fødevarer', 'Rengøring', 'Shampoo'],
    productSummary: 'Fødevarer, Rengøring, Shampoo',
    products: [
      { name: 'Økologisk Havregryn', price: '25 kr / kg', category: 'Fødevarer', inStock: true },
      { name: 'Flydende Vaskemiddel (Neutral)', price: '45 kr / L', category: 'Rengøring', inStock: true },
      { name: 'Shampoo (Birk & Aloe Vera)', price: '60 kr / L', category: 'Shampoo', inStock: true },
    ],
    rating: 4.8,
  },
  {
    id: 3,
    name: 'Råvarebutikken',
    address: 'Nørrebrogade 55, København',
    lat: 55.6921,
    lng: 12.5478,
    description: 'Økologi og rene råvarer. Kropspleje og husholdning i løssalg.',
    categories: ['Shampoo', 'Hudpleje', 'Vaskemiddel', 'Rengøring'],
    productSummary: 'Shampoo, Hudpleje, Vaskemiddel',
    products: [
      { name: 'Balsam-bar', price: '75 kr / stk', category: 'Hudpleje', inStock: true },
      { name: 'Universalrengøring', price: '30 kr / L', category: 'Rengøring', inStock: true },
      { name: 'Opvaskemiddel med citrus', price: '35 kr / L', category: 'Vaskemiddel', inStock: true },
    ],
    rating: 4.6,
  },
  {
    id: 4,
    name: 'EcoKbh Genfyld',
    address: 'Østerbrogade 102, København',
    lat: 55.7096,
    lng: 12.5819,
    description: 'Genopfyldning af hverdagsprodukter med fokus på miljømærker.',
    categories: ['Vaskemiddel', 'Rengøring', 'Shampoo'],
    productSummary: 'Vaskemiddel, Rengøring, Shampoo',
    products: [
      { name: 'Color Vaskemiddel', price: '40 kr / L', category: 'Vaskemiddel', inStock: true },
      { name: 'Skyllemiddel', price: '25 kr / L', category: 'Vaskemiddel', inStock: true },
      { name: 'Hjardemynte Shampoo', price: '55 kr / L', category: 'Shampoo', inStock: true },
    ],
    rating: 4.9,
  },
  {
    id: 5,
    name: 'Nordic Refill Station',
    address: 'Ved Ryparken Station, 2100 København Ø',
    lat: 55.71556,
    lng: 12.55972,
    description: 'Et lokalt refill-paradis lige ved Ryparken. Gør det nemt at genfylde kropspleje og sæbe på farten til og fra arbejde.',
    categories: ['Vaskemiddel', 'Shampoo', 'Hudpleje'],
    productSummary: 'Vaskemiddel, Shampoo, Hudpleje',
    products: [
      { name: 'Flydende Kropssæbe (Refill)', price: '40 kr / L', category: 'Hudpleje', inStock: true },
      { name: 'Shampoo (Uden parfume)', price: '45 kr / L', category: 'Shampoo', inStock: true },
      { name: 'Multirengøring', price: '30 kr / L', category: 'Vaskemiddel', inStock: true },
    ],
    rating: 4.7,
  },
  {
    id: 6,
    name: 'Aarhus Øko-Tap',
    address: 'Mejlgade 45, 8000 Aarhus C',
    lat: 56.150,
    lng: 10.217,
    description: 'Et fantastisk refill-spot i hjertet af Aarhus. Vi elsker at reducere plastik i Latinerkvarteret!',
    categories: ['Rengøring', 'Sæbe'],
    productSummary: 'Rengøring, Sæbe',
    products: [{ name: 'Håndsæbe Refill', price: '30 kr / L', category: 'Sæbe', inStock: true }],
    rating: 4.8,
  },
  {
    id: 7,
    name: 'Aalborg Genfyld',
    address: 'Vesterbro 12, 9000 Aalborg',
    lat: 57.050,
    lng: 9.917,
    description: 'Aalborgs bedste udvalg af emballagefri varer og vaskemiddel lige midt i byen.',
    categories: ['Vaskemiddel', 'Shampoo'],
    productSummary: 'Vaskemiddel, Shampoo',
    products: [{ name: 'Shampoo Bar', price: '65 kr / stk', category: 'Shampoo', inStock: true }],
    rating: 4.5,
  },
  {
    id: 8,
    name: 'Fynsk Refill',
    address: 'Vestergade 80, 5000 Odense C',
    lat: 55.396,
    lng: 10.389,
    description: 'Odenses originale løs-vægt butik med alt til husholdningen og masser af fynsk charme.',
    categories: ['Fødevarer', 'Hudpleje'],
    productSummary: 'Fødevarer, Hudpleje',
    products: [{ name: 'Ansigtscreme', price: '80 kr / 100 ml', category: 'Hudpleje', inStock: true }],
    rating: 4.9,
  },
];

export const ALL_CATEGORIES = [
  'Alle',
  'Shampoo',
  'Vaskemiddel',
  'Fødevarer',
  'Hudpleje',
  'Rengøring',
  'Balsam',
  'Sæbe',
];
